### ISSUE TITLE
Exposed "[window=..]" in link

### ISSUE THREAD

**Issue by sgeorgi** [reactivefoundation/reactiveprinciples#9]
VII. of the Reactive Principles seems to expose a typo/mishap in an anchor:

`[window="new tab"]`

<img width="790" alt="image" src="https://user-images.githubusercontent.com/83532/93258353-7222d400-f79e-11ea-9f90-2fbca1e54d23.png">

**Comment by jboner** [comment]
@sgeorgi Thanks for reporting it. 
@rstento Can you take a look at this?

**Comment by rstento** [comment]
Fixed with PR #10 and merged.
